// Where processed images live. Local disk today; the interface is what the
// rest of the API uses, so an S3-compatible store can replace LocalStore
// without touching business logic.
//
// Keys are generated by the server only ("l/2026/10/<uuid>") and checked
// against KEY_PATTERN before any filesystem call, so a key can never point
// outside the upload directory.
import { mkdir, rm, writeFile, stat } from "node:fs/promises";
import path from "node:path";

export const KEY_PATTERN = /^[la]\/[0-9]{4}\/[0-9]{2}\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
export const VARIANT_PATTERN = /^(sm|md|lg)\.webp$/;

export interface ObjectStore {
  /** Writes all variants of one image under `key`. */
  putVariants(key: string, variants: { name: string; data: Buffer }[]): Promise<void>;
  /** Removes an image and all its variants. Missing files are not an error. */
  remove(key: string): Promise<void>;
  /** Absolute path of a variant for serving, or null when it does not exist. */
  locate(key: string, variant: string): Promise<string | null>;
}

export function assertKey(key: string) {
  if (!KEY_PATTERN.test(key)) throw new Error("invalid storage key");
}

export class LocalStore implements ObjectStore {
  private root: string;

  constructor(root: string) {
    this.root = path.resolve(root);
  }

  private dir(key: string) {
    assertKey(key);
    const dir = path.resolve(this.root, key);
    if (!dir.startsWith(this.root + path.sep)) throw new Error("invalid storage key");
    return dir;
  }

  async putVariants(key: string, variants: { name: string; data: Buffer }[]) {
    const dir = this.dir(key);
    await mkdir(dir, { recursive: true, mode: 0o750 });
    for (const v of variants) {
      if (!VARIANT_PATTERN.test(v.name)) throw new Error("invalid variant name");
      await writeFile(path.join(dir, v.name), v.data, { mode: 0o640, flag: "wx" });
    }
  }

  async remove(key: string) {
    await rm(this.dir(key), { recursive: true, force: true });
  }

  async locate(key: string, variant: string) {
    if (!KEY_PATTERN.test(key) || !VARIANT_PATTERN.test(variant)) return null;
    const file = path.join(this.dir(key), variant);
    try {
      const s = await stat(file);
      return s.isFile() ? file : null;
    } catch {
      return null;
    }
  }
}
